site_name: "Sclera Documentation"

site_description: "Documentation for Sclera and its plugins"

site_author: "Sclera, Inc."

copyright: "Copyright &copy; 2012 - 2020 Sclera, Inc."

site_url: "https://www.scleradb.com/docs"

site_dir: docs

docs_dir: docsrc

nav:
    - 'Home': "/"
    - 'Documentation Contents': index.md
    - 'Introduction':
        - 'Why Sclera?': intro/whysclera.md
        - 'FAQ': intro/faq.md
        - 'Technical Details': intro/technical.md
    - 'Setup':
        - 'Components Reference': setup/components.md
        - 'Installation Reference': setup/install.md
        - 'Data Platform Connection Reference': setup/dbms.md
        - 'Configuration Reference': setup/configuration.md
    - 'ScleraSQL':
        - 'ScleraSQL Examples': sclerasql/sqlexamples.md
        - 'ScleraSQL Introduction': sclerasql/sqlintro.md
        - 'Standard SQL': sclerasql/sqlregular.md
        - 'Using Cross-Tabulation': sclerasql/sqlcrosstab.md
        - 'Processing Ordered Data': sclerasql/sqlextordered.md
        - 'Sequence Alignment': sclerasql/sqlseqalign.md
        - 'Selecting the Optimal': sclerasql/sqlextarg.md
        - 'Using Machine Learning': sclerasql/sqlextml.md
        - 'Data Cleaning': sclerasql/sqlcleaning.md
        - 'Using Text Analytics': sclerasql/sqlexttext.md
        - 'External Data Access': sclerasql/sqlextdataaccess.md
        - 'Visualization': sclerasql/visualization.md
        - 'Miscellaneous Information': sclerasql/sqlmisc.md
    - 'Interface':
        - 'Command Line Shell Reference': interface/shell.md
        - 'Embedded JDBC Reference': interface/jdbc.md
    - 'Sclera Extensions SDK':
        - 'Extensions SDK Introduction': sdk/sdkintro.md
        - 'Data Access Plugins': sdk/sdkextdataaccess.md
        - 'Database System Plugins': sdk/sdkextdbms.md
        - 'Machine Learning Library Plugins': sdk/sdkextml.md
        - 'Text Analytics Library Plugins': sdk/sdkexttext.md
    - 'Acknowledgements':
        - 'Component Third Party Dependencies': ack/dependencies.md
        - 'Component Licenses': ack/licenses.md

theme:
    name: "material"
    logo: "../images/sclera-logo-square.png"
    favicon: "../images/icons/favicon.ico"
    palette:
        primary: 'black'
        accent: 'indigo'
    font:
        text: 'Open Sans'
        code: 'Courier Prime'

extra_css:
    - ../css/docs.css

extra:
    social:
        - type: "github"
          link: "https://github.com/scleradb"
        - type: "twitter"
          link: "https://twitter.com/scleradb"
        - type: "linkedin"
          link: "https://www.linkedin.com/company/sclera-inc-"
    manifest: "../images/icons/site.webmanifest"

markdown_extensions:
    - toc:
        permalink: "&#9668;"

google_analytics: ['UA-47770601-1', 'scleradb.com']
